tags:
  - name: Test API Swagger
get:
  description: None
parameters:
  - name: text
    in: formData
    required: false
    type: text
responses:
  "200":
    description: Sucessful response
  "400":
    description: Bad Request
  "500":
    description: Internal Server Error