tags:
  - name: Test API Swagger
get:
  description: None
responses:
  "200":
    description: Succesful response
  "400":
    description: Bad Request
  "500":
    description: Internal Server Error
parameters:
  - name: file
    in: formData
    type: file
    description: The file to upload.